export const DRAWER_TYPES = {
    CLIENT_REQUEST: 'CLIENT_REQUEST',
    TESTIMONIAL: 'TESTIMONIAL'
}

export const FORM_ACTIONS = {
    UPDATE: 'UPDATE',
    RESET: 'RESET',
    IMPORT: 'IMPORT'
}

export const SELECT_ACTIONS = {
    SHOW: 'SHOW',
    HIDDEN: 'HIDDEN',
    LOW_RATING: 'LOW_RATING',
    HIGH_RATING: 'HIGH_RATING',
    NEWEST: 'NEWEST',
    OLDEST: 'OLDEST'
}
